name: Deploy on production

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Run commands on EC2 server
    runs-on: ubuntu-latest

    steps:
    - name: Execute commands via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 13.126.170.144
        username: "oh"
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "hello"
          whoami
